### ISSUE TITLE
Add workout item

### ISSUE THREAD

**Issue by christopher-stone** [wford7/AndroidStudio#1]
Add ability to create a new schedule into which to put new workouts.

**Comment by awrigh36** [comment]
Task switched to implement add/edit workouts base feature. Schedule is no longer an object.

**Comment by christopher-stone** [comment]
Code nearly complete. Issue rolling over to Sprint 2.

**Comment by christopher-stone** [comment]
Code nearly complete. Issue rolling over to Sprint 3.

**Comment by christopher-stone** [comment]
Nearly complete. Rolling over to Sprint 4.

**Comment by christopher-stone** [comment]
This issue was moved to GymRatTrax/GymRatTrax#1
