### ISSUE TITLE
View/edit workout items

### ISSUE THREAD

**Issue by christopher-stone** [wford7/AndroidStudio#2]
Users can modify schedules where necessary and then use said schedules as a reference when creating their future fitness goals.

**Comment by awrigh36** [comment]
Changed task to edit existing workout items.

**Comment by christopher-stone** [comment]
Code nearly complete. Issue rolling over to Sprint 2.

**Comment by christopher-stone** [comment]
Code nearly complete. Issue rolling over to Sprint 3.

**Comment by christopher-stone** [comment]
Nearly complete. Rolling over to Sprint 4.

**Comment by christopher-stone** [comment]
This issue was moved to GymRatTrax/GymRatTrax#2
