### ISSUE TITLE
New user Profile check (Create Fitness Profile before main menu access)

### ISSUE THREAD

**Issue by christopher-stone** [wford7/AndroidStudio#7]
Application initialization will ask specific information from the user that will help calculations.

**Comment by wford7** [comment]
3/14 - New user profile setup activity created.  If profile does not exist at start up, new profile setup activity is created.

**Comment by christopher-stone** [comment]
Functionality basically working as intended. Resolved as designed.

**Comment by christopher-stone** [comment]
This issue was moved to GymRatTrax/GymRatTrax#7
